name: dfm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - cudatoolkit=12.1  # 明确指定 CUDA 工具包版本
  - omegaconf>=2.3.0
  - matplotlib>=3.8.1
  - pip=23.3
  - pytorch=2.2.0  # 升级到 2.2.0 以匹配 CUDA 12.1
  - pytorch-cuda=12.1  # 与 CUDA 驱动兼容
  - pip:
      - torch==2.2.0+cu121  # 强制指定 CUDA 版本
      - torchvision==0.17.0+cu121
      - torchaudio==2.2.0+cu121
      - xformers==0.0.24  # 升级 xformers 版本
      - diffusers==0.26.3
      - transformers==4.35.0
      - einops==0.7.0
      - torchdiffeq==0.2.3
      - huggingface_hub==0.25.0
      - numpy==1.26.0  # 固定 NumPy 版本避免兼容性问题