name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    # 动态生成 environment.yml
    - name: Generate environment.yml dynamically
      run: |
        cat <<EOF > environment.yml
        name: dfm
        channels:
          - defaults
          - conda-forge
        dependencies:
          - python=3.12
          - pip
          - pip:
            - -r requirements.txt
        EOF

    # 使用 Miniconda 管理环境
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12
        activate-environment: dfm
        environment-file: environment.yml
        auto-activate-base: false

    # 安装项目依赖
    - name: Install dependencies from requirements.txt
      run: |
        pip install -r requirements.txt

    # 安装测试工具（flake8 和 pytest）
    - name: Install testing tools
      run: |
        pip install flake8 pytest

    # 代码检查
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # 运行测试
    - name: Test with pytest
      run: |
        pytest
